### ISSUE TITLE
Invalid masters entry in metadata/layout.conf

### ISSUE THREAD

**Issue by NP-Hardass** [austin987/wizardedit-overlay#3]
the masters value is sort of like a repository inheritance specifier (go to these repos if what you need isn't in this repo).  Specifying your own overlay in the masters is invalid.

**Comment by austin987** [comment]
Fixed by https://github.com/austin987/wizardedit-overlay/commit/7403091fdd08d96895fa5f3e7ea17f3b0610edfb
